# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9c863c3bbe4fd6335f4c5ffc4241d293c80a63bb9c246b528f79479035bd9b04d45662afe608c49e9bc9ee72c13539c8aeb1e0b887863d9bfa055263cf59c1e8

test:
  secret_key_base: 3ba8c18c793f9262adf2431b0de7ce583427a0438276810173fcf2179fca2d3bfa01ad8b4cd1767c567336c32a85bd12d6f81877419ed215fb9f78e0dea41bb6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
